mysql: &mysql
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: 5
  host: localhost
  username: root
  password: root
  port: 3306

development:
  <<: *mysql
  database: video_recorder_dev

production:
  <<: *mysql
  database: video_recorder_prod
